-- ============================================================================
-- Bluy - stories schema + seed (generated from src/data/stories.ts)
-- Run in Supabase: SQL Editor -> New query -> paste this file -> Run.
-- Safe to re-run: tables use "if not exists" and rows use upserts.
-- ============================================================================

create table if not exists public.authors (
  id   text primary key,
  name text not null,
  bio  text
);

create table if not exists public.stories (
  id           text primary key,
  title        text not null,
  author_id    text references public.authors(id),
  format       text not null,
  genres       text[] not null default '{}',
  blurb        text,
  description  text,
  cover_color  text,
  cover_emoji  text,
  is_complete  boolean not null default false,
  rating       numeric not null default 0,
  reads_count  integer not null default 0,
  created_at   timestamptz not null default now()
);

create table if not exists public.chapters (
  story_id        text not null references public.stories(id) on delete cascade,
  id              text not null,
  "order"         integer not null,
  title           text not null,
  reading_minutes integer not null default 1,
  is_premium      boolean not null default false,
  paragraphs      text[] not null default '{}',
  primary key (story_id, id)
);

-- Public read access (readers browse without logging in); no public writes.
alter table public.authors  enable row level security;
alter table public.stories  enable row level security;
alter table public.chapters enable row level security;

drop policy if exists "authors_public_read" on public.authors;
create policy "authors_public_read" on public.authors for select using (true);
drop policy if exists "stories_public_read" on public.stories;
create policy "stories_public_read" on public.stories for select using (true);
drop policy if exists "chapters_public_read" on public.chapters;
create policy "chapters_public_read" on public.chapters for select using (true);


-- Authors
insert into public.authors (id, name, bio) values ($b$rosa$b$, $b$Rosa Delacroix$b$, $b$Writes quiet fantasy about ordinary people in extraordinary woods.$b$) on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.authors (id, name, bio) values ($b$mensah$b$, $b$K. A. Mensah$b$, $b$Former detective turned crime novelist. Likes a locked room.$b$) on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.authors (id, name, bio) values ($b$tan$b$, $b$Junie Tan$b$, $b$Science fiction about the small lives inside big machines.$b$) on conflict (id) do update set name = excluded.name, bio = excluded.bio;
insert into public.authors (id, name, bio) values ($b$okafor$b$, $b$Ada Okafor$b$, $b$Love stories with sharp edges and soft landings.$b$) on conflict (id) do update set name = excluded.name, bio = excluded.bio;

-- Stories
insert into public.stories (id, title, author_id, format, genres, blurb, description, cover_color, cover_emoji, is_complete, rating, reads_count) values ($b$lantern-in-the-pines$b$, $b$The Lantern in the Pines$b$, $b$rosa$b$, $b$serial$b$, array[$b$Fantasy$b$, $b$Mystery$b$], $b$A lamplighter follows a light that should not exist.$b$, $b$Every winter the village of Hollowmere lights its lanterns against the dark. This year a new light burns deep in the pines — steady, patient, and waiting. Maren, the youngest lamplighter the village has ever named, is the only one who can see it. A slow-burning fantasy serial, updated weekly.$b$, $b$#2F6F4E$b$, $b$🏮$b$, false, 4.7, 18420) on conflict (id) do update set title = excluded.title, author_id = excluded.author_id, format = excluded.format, genres = excluded.genres, blurb = excluded.blurb, description = excluded.description, cover_color = excluded.cover_color, cover_emoji = excluded.cover_emoji, is_complete = excluded.is_complete, rating = excluded.rating, reads_count = excluded.reads_count;
insert into public.stories (id, title, author_id, format, genres, blurb, description, cover_color, cover_emoji, is_complete, rating, reads_count) values ($b$glasshouse-murders$b$, $b$The Glasshouse Murders$b$, $b$mensah$b$, $b$serial$b$, array[$b$Mystery$b$, $b$Thriller$b$], $b$Three guests. One locked greenhouse. No way in or out.$b$, $b$When botanist Iris Vale is found dead inside a greenhouse locked from the inside, Inspector Cole has a problem: the only three people with keys all have alibis, and the orchids aren’t talking. A complete, three-part locked-room mystery.$b$, $b$#7A3B69$b$, $b$🔍$b$, true, 4.5, 9650) on conflict (id) do update set title = excluded.title, author_id = excluded.author_id, format = excluded.format, genres = excluded.genres, blurb = excluded.blurb, description = excluded.description, cover_color = excluded.cover_color, cover_emoji = excluded.cover_emoji, is_complete = excluded.is_complete, rating = excluded.rating, reads_count = excluded.reads_count;
insert into public.stories (id, title, author_id, format, genres, blurb, description, cover_color, cover_emoji, is_complete, rating, reads_count) values ($b$last-train-to-vega$b$, $b$Last Train to Vega$b$, $b$tan$b$, $b$serial$b$, array[$b$Sci-Fi$b$], $b$A night-shift conductor on a train between stars.$b$, $b$The Vega Line runs once a decade, carrying sleepers across thirty light-years while they dream. Sol is the only one awake — the conductor, the witness, the keeper of other people’s journeys. Then a passenger wakes up early. An ongoing space serial.$b$, $b$#2B4C7E$b$, $b$🚆$b$, false, 4.6, 12030) on conflict (id) do update set title = excluded.title, author_id = excluded.author_id, format = excluded.format, genres = excluded.genres, blurb = excluded.blurb, description = excluded.description, cover_color = excluded.cover_color, cover_emoji = excluded.cover_emoji, is_complete = excluded.is_complete, rating = excluded.rating, reads_count = excluded.reads_count;
insert into public.stories (id, title, author_id, format, genres, blurb, description, cover_color, cover_emoji, is_complete, rating, reads_count) values ($b$salt-and-other-cures$b$, $b$Salt and Other Cures$b$, $b$okafor$b$, $b$standalone$b$, array[$b$Literary$b$, $b$Romance$b$], $b$Two strangers, one storm, and a seaside town that keeps secrets in brine.$b$, $b$A complete short story. When a storm strands a grieving chef in a town that preserves everything — fish, fruit, grudges, love — she finds the one recipe she never learned to make: starting over.$b$, $b$#C26B3E$b$, $b$🧂$b$, true, 4.8, 24110) on conflict (id) do update set title = excluded.title, author_id = excluded.author_id, format = excluded.format, genres = excluded.genres, blurb = excluded.blurb, description = excluded.description, cover_color = excluded.cover_color, cover_emoji = excluded.cover_emoji, is_complete = excluded.is_complete, rating = excluded.rating, reads_count = excluded.reads_count;
insert into public.stories (id, title, author_id, format, genres, blurb, description, cover_color, cover_emoji, is_complete, rating, reads_count) values ($b$letters-we-never-sent$b$, $b$Letters We Never Sent$b$, $b$okafor$b$, $b$standalone$b$, array[$b$Romance$b$], $b$A box of unsent letters, found forty years too late.$b$, $b$A complete short story, available to subscribers. When Tomas inherits his late grandmother’s house, he finds a shoebox of letters addressed to a man no one in the family has ever heard of — all written, none sent.$b$, $b$#A23E54$b$, $b$💌$b$, true, 4.9, 15780) on conflict (id) do update set title = excluded.title, author_id = excluded.author_id, format = excluded.format, genres = excluded.genres, blurb = excluded.blurb, description = excluded.description, cover_color = excluded.cover_color, cover_emoji = excluded.cover_emoji, is_complete = excluded.is_complete, rating = excluded.rating, reads_count = excluded.reads_count;
insert into public.stories (id, title, author_id, format, genres, blurb, description, cover_color, cover_emoji, is_complete, rating, reads_count) values ($b$weight-of-small-hours$b$, $b$The Weight of Small Hours$b$, $b$tan$b$, $b$standalone$b$, array[$b$Literary$b$], $b$A night nurse, an insomniac city, and the things people confess at 3 a.m.$b$, $b$A complete short story. On the quietest ward of a sleepless hospital, the things patients say between midnight and dawn are not the things they say in daylight. A nurse learns to carry them.$b$, $b$#3F5E5A$b$, $b$🌙$b$, true, 4.4, 6240) on conflict (id) do update set title = excluded.title, author_id = excluded.author_id, format = excluded.format, genres = excluded.genres, blurb = excluded.blurb, description = excluded.description, cover_color = excluded.cover_color, cover_emoji = excluded.cover_emoji, is_complete = excluded.is_complete, rating = excluded.rating, reads_count = excluded.reads_count;

-- Chapters
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$lantern-in-the-pines$b$, $b$ch1$b$, 1, $b$The Light That Wasn’t Lit$b$, 1, false, array[$b$Maren had lit three hundred and twelve lanterns in her life, and not one of them had ever frightened her until tonight.$b$, $b$The cold in Hollowmere came down from the mountains like a tide, and against it the village kept its old bargain: every lantern lit by dusk, every flame fed until dawn. Her grandmother had taught her the rhythm of it — wick, spark, breath, move on — and Maren could walk the whole circuit in her sleep, which on the long nights she very nearly did.$b$, $b$So when she reached the edge of the pines and saw a light already burning where no lantern stood, her hands forgot the rhythm entirely.$b$, $b$It was the wrong color. Village flame was warm and yellow, the color of butter and safety. This light was pale, almost green, and it did not flicker the way fire flickers. It simply waited, deep among the trunks, as if it had been left on for her.$b$, $b$“Hello?” she called, and felt foolish at once. Lights do not answer. But this one, impossibly, grew a little brighter — the way a person leans forward when they have finally been seen.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$lantern-in-the-pines$b$, $b$ch2$b$, 2, $b$What the Snow Remembers$b$, 1, false, array[$b$In the morning Maren told no one. There was no one to tell who would believe her, and several who would worry, which was worse.$b$, $b$Instead she went back to the tree line in daylight, when the woods were only woods and the snow lay clean and unbothered. She found the spot easily — she had not slept for thinking of it — and there, pressed into the drift, were footprints leading away into the pines.$b$, $b$They were her size. They were, she realized with a slow cold horror that had nothing to do with the weather, exactly her size, down to the worn left heel of her own boots. But she had not stepped off the path. She was certain she had not stepped off the path.$b$, $b$The snow, it seemed, remembered something she did not.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$lantern-in-the-pines$b$, $b$ch3$b$, 3, $b$The Keeper of the Far Lamp$b$, 1, true, array[$b$The figure at the heart of the pines was not a ghost, though Maren had prepared herself for a ghost and felt almost cheated.$b$, $b$He was old in the way the trees were old — not frail, but layered, as though many winters had been folded into one man and pressed flat. He held the pale lantern without seeming to hold it at all.$b$, $b$“You came back,” he said. “They usually don’t. They tell themselves it was a trick of the cold.” He studied her with eyes that caught the green light and kept it. “But you’re a lamplighter. You can’t leave a flame unexplained. It itches.”$b$, $b$Maren’s mouth was dry. “What are you keeping lit out here?”$b$, $b$The old man smiled, and for the first time the lantern flickered — once, like a held breath finally let go. “The way back,” he said. “For everyone Hollowmere has ever lost. Someone has to keep it burning. My hands are getting tired, child. I have been hoping, for a very long time, that someone with steady hands might come and see.”$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$lantern-in-the-pines$b$, $b$ch4$b$, 4, $b$Steady Hands$b$, 1, true, array[$b$There is a moment in every apprenticeship where the teacher stops explaining and simply hands you the work. Maren had felt it before, the night her grandmother pressed the village taper into her palm and stepped back.$b$, $b$She felt it now, in the dark of the pines, as the old keeper held out the pale lantern and waited.$b$, $b$“If I take it,” she said slowly, “can I put it down again?”$b$, $b$“That,” he said, “is the only honest question anyone has ever asked me out here. And the answer is yes — but you won’t want to. That is the trick of it. Not the weight. The wanting.”$b$, $b$Maren looked back the way she had come, toward the warm and ordinary lights of home, each one lit by her own hand. Then she looked at the cold green flame that lit the way to everywhere else. She thought about her grandmother. She thought about all the names the village said quietly and never expected to say again.$b$, $b$She reached out.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$glasshouse-murders$b$, $b$ch1$b$, 1, $b$A Door That Only Locks From Within$b$, 1, false, array[$b$The greenhouse had one door, and that door had been bolted from the inside. Inspector Cole had confirmed it twice, because the first time he had not believed it either.$b$, $b$Iris Vale lay among her orchids as though she had simply decided to rest there. No wound he could see. No struggle. The humid air held the green smell of growing things and, underneath it, something sharper he could not yet name.$b$, $b$“Three people had keys,” said the constable. “The husband, the assistant, and the gardener. All three were somewhere else. We checked.”$b$, $b$Cole crouched by the body and looked, for a long moment, at the single orchid clutched in her hand — a flower he was fairly sure had not been blooming anywhere else in the room.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$glasshouse-murders$b$, $b$ch2$b$, 2, $b$Everyone Has an Alibi$b$, 1, false, array[$b$The husband had been at his club, witnessed by twelve men and a great deal of brandy. The assistant had been on a train, ticket stamped. The gardener had been in the village pub until closing, loudly and memorably.$b$, $b$“It’s a good problem,” Cole admitted to the constable, “when everyone can prove where they were. It means someone went to a great deal of trouble. People only build alibis that neat when they expect to need them.”$b$, $b$He spread the three keys on the table. Identical brass, identical teeth. Except — he held one to the light — one of them was very slightly warm, as though it had been carried close to the body, in a pocket, all evening.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$glasshouse-murders$b$, $b$ch3$b$, 3, $b$The Flower That Told the Truth$b$, 1, false, array[$b$It was the orchid that undid them in the end.$b$, $b$Iris Vale had been cultivating a single impossible hybrid, a flower that bloomed for one hour a year. She had told exactly one person the night it would open. That person had come to see it — not to kill her, perhaps, but to take it — and in the small struggle that followed, a sealed room had become a sealed tomb.$b$, $b$“You locked it behind you,” Cole said quietly, “out of habit. She always locked it. You’d watched her do it a hundred times. You weren’t thinking about an alibi. You were thinking about the flower.”$b$, $b$The assistant’s hands, which had been so steady all week, finally began to shake.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$last-train-to-vega$b$, $b$ch1$b$, 1, $b$Awake$b$, 1, false, array[$b$There are four hundred sleepers aboard the Vega Line and exactly one person awake to mind them, and for nine years that person has been Sol.$b$, $b$It is not a lonely job, Sol tells the recruiters, which is a lie everyone agrees to. It is the loneliest job that exists. You walk the long aisle between the pods and you watch four hundred faces dream, and you keep the lights low, and you do not — you must not — open any of them early.$b$, $b$On the three-thousand-and-first night, pod 114 begins, very softly, to chime.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$last-train-to-vega$b$, $b$ch2$b$, 2, $b$The Passenger Who Shouldn’t Be$b$, 1, true, array[$b$Her name, according to the manifest, was Ren, and she was not due to wake for another six years.$b$, $b$“How long have I been under?” she asked, before she had even fully sat up. It was the right question. Most early-wakers asked where they were. The good ones asked when.$b$, $b$“Three years,” Sol said. “You’ve got six to go. The pod shouldn’t have opened. I need to know if you touched anything before you slept.”$b$, $b$Ren looked at her hands as though they belonged to someone else. “I don’t think I went to sleep at all,” she said. “I think I was put to sleep. There’s a difference. And I think,” she added, meeting Sol’s eyes, “that you already know that, or you wouldn’t be whispering.”$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$last-train-to-vega$b$, $b$ch3$b$, 3, $b$What the Manifest Left Out$b$, 1, true, array[$b$Sol had read the manifest a thousand times on a thousand quiet nights. Four hundred names, four hundred destinations, four hundred small stories paused mid-sentence.$b$, $b$What Sol had never done was count them.$b$, $b$They counted now, together, pod by pod down the long cold aisle, and when they reached the end the number was four hundred and one. One more sleeper than the manifest admitted. One more face that no one was supposed to be awake to see.$b$, $b$“We are not going to Vega,” Ren said softly. “Are we.”$b$, $b$Sol did not answer. The lights hummed. The extra pod, far down the aisle, began very softly to chime.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$salt-and-other-cures$b$, $b$ch1$b$, 1, $b$Salt and Other Cures$b$, 1, false, array[$b$The town cured everything in salt, including, Naomi suspected, its own people. They had that look — preserved, a little too well kept, as though nothing here ever quite spoiled and nothing ever quite ripened either.$b$, $b$She had not meant to stop. The storm had stopped her, the way storms do, folding the road into the sea somewhere behind her and leaving only this: a harbor, a shuttered inn, and a man on the dock mending nets in the rain as though the rain were a minor disagreement he expected to win.$b$, $b$“Kitchen’s closed,” he said, without looking up. “But the kettle isn’t.” And that, in the end, was the whole of how it began — not with a recipe, but with someone offering her something warm before she had to ask.$b$, $b$Naomi had spent two years cooking for a man who was no longer alive to taste it. She had salted everything those two years, she realized now, watching the harbor blur. Preserving meals he would never come home for. Keeping things that were already gone.$b$, $b$The man set the kettle down between them and finally looked at her — not with pity, which she had grown to hate, but with the plain curiosity of someone who had all the time in the world and no particular need to fill it.$b$, $b$“You can stay till it passes,” he said. The storm, he meant. But she heard the other thing underneath it, the thing this whole salt-kept town seemed to know how to say without saying: some things, if you tend them right, keep. And some things are meant, at last, to be let go.$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$letters-we-never-sent$b$, $b$ch1$b$, 1, $b$Letters We Never Sent$b$, 2, true, array[$b$The shoebox was at the back of the wardrobe, behind the good coat his grandmother had been saving, his whole life, for an occasion that apparently never came.$b$, $b$Inside were forty-one letters, tied with a ribbon gone soft as cloth. Each was addressed in his grandmother’s careful hand to a man named Aurelio, at an address in a city she had, to Tomas’s knowledge, never once visited. None of them had stamps. None had been opened, because none had ever been sent.$b$, $b$He read the first one sitting on the floor of the empty bedroom, and by the third he understood that he had known his grandmother for thirty years and not at all.$b$, $b$“My dear Aurelio,” the first one began. “I am marrying him on Sunday. He is kind, and I will be a good wife, and I am writing to you instead of to my own heart because my heart, I find, will not listen to reason. This is the last foolish thing I will allow myself. After this, I will be sensible for the rest of my life.”$b$, $b$There were forty more. She had not, it turned out, managed to be sensible at all. She had simply learned to keep her foolishness in a box, and to love a man named Aurelio quietly, in unsent letters, for forty years — while loving the kind man she married out loud, every single day.$b$, $b$Tomas sat for a long time in the dust and the late light. Then he did the only thing that seemed right. He found the fortieth letter, the one dated just weeks before she died, and he read the last line his grandmother ever wrote to a man she never sent a word to: “If you are reading this, then someone braver than I was has finally posted it. Be kind to them. They have just learned that love is mostly the things we never said.”$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
insert into public.chapters (story_id, id, "order", title, reading_minutes, is_premium, paragraphs) values ($b$weight-of-small-hours$b$, $b$ch1$b$, 1, $b$The Weight of Small Hours$b$, 1, false, array[$b$Between midnight and four, the hospital tells the truth. Priya has worked the night shift long enough to know the schedule of honesty: visitors gone, painkillers settling, the daylight performance of being fine finally too heavy to hold up.$b$, $b$That is when they talk. Not about their charts. About the brother they haven’t called in nine years. About the thing they said to their daughter that they would give a lung to take back. About being afraid, plainly, the way children are afraid, of the dark and of the morning both.$b$, $b$Priya does not fix any of it. She has learned that this is not the job, though it took her years to believe it. The job is simply to be awake when they are, to hold the small hours steady so the confessions have somewhere to land.$b$, $b$“Will you remember what I said?” old Mr. Adeyemi asks her, near the end of his last night, and she takes his hand and tells him the truest thing she knows: “I remember all of it. That’s what I’m here for. You can put it down now. I’ve got it.”$b$]) on conflict (story_id, id) do update set "order" = excluded."order", title = excluded.title, reading_minutes = excluded.reading_minutes, is_premium = excluded.is_premium, paragraphs = excluded.paragraphs;
