import { useRouter } from 'expo-router';
import { useMemo } from 'react';

/**
 * The handful of navigations the landing's buttons trigger, in one place so the
 * cinematic and calm variants stay in sync. `markSeen` is called on any action
 * that leaves the landing so the intro doesn't replay when the visitor comes
 * back to `/`.
 */
export function useLandingActions(markSeen: () => void) {
  const router = useRouter();
  return useMemo(() => {
    const go = (href: string) => {
      markSeen();
      // expo-router's typed-route union is generated by the dev server; cast is safe.
      router.push(href as never);
    };
    return {
      onPrimary: () => go('/auth'), // ENTER THE STORY → create account / sign in
      onSecondary: () => go('/explore'), // EXPLORE STORIES
      onSignIn: () => go('/auth'),
      onRegister: () => go('/auth'),
      onExplore: () => go('/explore'),
      onNav: (href: string) => go(href),
    };
  }, [router, markSeen]);
}
