import { DarkTheme, DefaultTheme, Stack, ThemeProvider, useRouter } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { useEffect } from 'react';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import { AppStateProvider } from '@/context/app-state';
import { AuthProvider } from '@/context/auth';
import { StoriesProvider } from '@/context/stories';
import { AppThemeProvider, useThemeMode } from '@/context/theme';
import { supabase } from '@/lib/supabase';

export default function RootLayout() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaProvider>
        <AppThemeProvider>
          <AuthProvider>
            <AppStateProvider>
              <StoriesProvider>
                <RootNav />
              </StoriesProvider>
            </AppStateProvider>
          </AuthProvider>
        </AppThemeProvider>
      </SafeAreaProvider>
    </GestureHandlerRootView>
  );
}

function RootNav() {
  const { isDark } = useThemeMode();
  const router = useRouter();

  // When a password-reset email link is opened, Supabase fires PASSWORD_RECOVERY
  // as it reads the token from the URL. Send the user to the set-password screen —
  // otherwise the new recovery session just drops them on the home screen "logged in".
  useEffect(() => {
    if (!supabase) return;
    const { data: sub } = supabase.auth.onAuthStateChange((event) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any -- expo's typed-routes union
      // is only regenerated by the dev server, so it doesn't yet know this route at typecheck time.
      if (event === 'PASSWORD_RECOVERY') router.replace('/reset-password' as any);
    });
    return () => sub.subscription.unsubscribe();
  }, [router]);

  return (
    <ThemeProvider value={isDark ? DarkTheme : DefaultTheme}>
      <Stack>
        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        <Stack.Screen name="reset-password" options={{ headerShown: false }} />
        <Stack.Screen name="story/[id]" options={{ headerShown: false, presentation: 'card' }} />
        <Stack.Screen name="reader/[storyId]/[chapterId]" options={{ headerShown: false }} />
        <Stack.Screen name="paywall" options={{ headerShown: false, presentation: 'modal' }} />
        <Stack.Screen name="auth" options={{ headerShown: false, presentation: 'modal' }} />
        <Stack.Screen name="write" options={{ headerShown: false, presentation: 'modal' }} />
        <Stack.Screen name="add-chapter" options={{ headerShown: false, presentation: 'modal' }} />
        <Stack.Screen name="settings" options={{ headerShown: false, presentation: 'card' }} />
      </Stack>
      <StatusBar style={isDark ? 'light' : 'dark'} />
    </ThemeProvider>
  );
}
